---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_pip_interpreter: /usr/lib/python3/dist-packages
    user: kyleandrei
 
  become: true
  tasks:

  - name: install python3, pip, and java open-jdk
    apt:
      name:
        - python3
        - pip
        - default-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install python3, pip, and java open-jdk
    dnf:
      name:
        - python3
        - python3-pip
        - java-11-openjdk-devel
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: set motd
    net_banner:
      banner: motd
      text: |
        Ansible Managed node by (user)
      state: present
 
